tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "asciinema"
brew "cairo"
brew "gh"
brew "httpie"
brew "mas"
brew "neofetch"
brew "starship"
brew "tldr"
brew "yarn"
brew "youtube-dl"
cask "bitwarden"
cask "chromium"
cask "discord"
cask "github"
cask "grammarly"
cask "microsoft-teams"
cask "slack"
cask "transmission"
cask "visual-studio-code"
mas "AdGuard for Safari", id: 1440147259
mas "Grammarly for Safari", id: 1462114288
mas "Xcode", id: 497799835
